-- =====================================================================
-- 005_transaction_partitions — SQLite compatible version.
-- SQLite does not support partitions; this migration is a no-op.
-- =====================================================================
